import { useCallback, useEffect, useState } from 'react';
import { useJournal } from '@/app/JournalContext';
import { goBack } from '@/app/router';
import { useAuth } from '@/core/auth/AuthContext';
import { supabase } from '@/core/auth/supabase';
import { callAi, type AiResponse, type AnswerOutput, type StoredReview } from '@/core/ai/client';
import { Icon } from '@/core/design/icons';
import { EmptyState, Section, Sheet, Toggle } from '@/core/design/ui';
import { formatShortDate } from '@/core/time/localDate';

interface Proposal { id: string; before_value: { energy_kcal: number | null; protein_g: number | null }; after_value: { energy_kcal: number | null; protein_g: number | null; rationale?: string }; status: string }
interface Memory { id: string; fact: string }
interface Usage { photo_today: number; questions_today: number; reviews_week: number; limits: { photo_per_day: number; question_per_day: number; review_per_week: number } }

const STARTERS = ['How consistent was I this week?', 'What should I focus on in my next workout?', 'Am I getting enough protein on the days I logged?'];

function errorText(r: AiResponse): string {
  if (r.status === 'error') {
    if (r.error === 'not_configured') return 'The coach isn’t switched on yet. The owner needs to add the AI settings (see the owner guide). Logging works as usual.';
    if (r.error === 'limit_user') return r.message;
    if (r.error === 'ai_paused') return 'The coach is paused for this month’s budget. Logging works as usual.';
    return r.message;
  }
  if (r.status === 'insufficient_data' || r.status === 'safety') return r.message;
  return '';
}

function ReviewView({ review, proposal, onDecide }: { review: StoredReview; proposal: Proposal | null; onDecide: (accept: boolean) => void }) {
  const o = review.output;
  const c = review.data_completeness;
  return (
    <div className="stack">
      <div className="row wrap" style={{ gap: 6 }}>
        <span className="tag coach">{formatShortDate(review.data_period.from)} – {formatShortDate(review.data_period.to)}</span>
        <span className="tag">{c.days_with_meals}/7 days with meals</span>
        <span className="tag">{c.sessions} workout{c.sessions === 1 ? '' : 's'}</span>
        <span className="tag">{c.weight_points} weigh-in{c.weight_points === 1 ? '' : 's'}</span>
      </div>
      {o.observations.length ? (
        <div className="review-block">
          <h3>What your logs show</h3>
          <ul>{o.observations.map((x, i) => <li key={i}>{x.text}</li>)}</ul>
        </div>
      ) : null}
      {o.suggestions.length ? (
        <div className="review-block">
          <h3>Suggested next step</h3>
          <ul>{o.suggestions.map((x, i) => <li key={i}>{x.text}{x.uncertainty !== 'low' ? <span className="label"> · {x.uncertainty === 'high' ? 'uncertain' : 'somewhat uncertain'}</span> : null}</li>)}</ul>
        </div>
      ) : null}
      {o.missing_information.length || o.questions.length ? (
        <div className="review-block">
          <h3>Missing information</h3>
          <ul>{[...o.missing_information, ...o.questions].map((x, i) => <li key={i}>{x}</li>)}</ul>
        </div>
      ) : null}
      {proposal && proposal.status === 'proposed' ? (
        <div className="card flat stack-sm" style={{ background: 'var(--coach)', borderColor: 'transparent' }}>
          <strong>Proposed target change</strong>
          <div className="before-after">
            <div><div className="label">Now</div><div className="num">{proposal.before_value.energy_kcal ?? '—'} kcal<br />{proposal.before_value.protein_g ?? '—'} g protein</div></div>
            <Icon name="chevronRight" />
            <div><div className="label">Proposed</div><div className="num"><strong>{proposal.after_value.energy_kcal ?? '—'} kcal<br />{proposal.after_value.protein_g ?? '—'} g protein</strong></div></div>
          </div>
          {proposal.after_value.rationale ? <p className="small">{proposal.after_value.rationale}</p> : null}
          <div className="row">
            <button className="btn secondary grow" onClick={() => onDecide(false)}>Keep current</button>
            <button className="btn grow" onClick={() => onDecide(true)}>Accept</button>
          </div>
          <p className="label">Nothing changes unless you accept. Check big changes with a qualified professional.</p>
        </div>
      ) : proposal ? <p className="label">Target proposal {proposal.status === 'accepted' ? 'accepted' : 'kept as it was'}.</p> : null}
      <p className="label">Generated by {review.model_id} from your own records. It can be wrong; it isn’t medical advice.</p>
    </div>
  );
}

export function CoachScreen() {
  const { mode, profile, updateProfile, today, notify } = useJournal();
  const { exitDemo } = useAuth();
  const online = navigator.onLine;
  const [review, setReview] = useState<StoredReview | null>(null);
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const [usage, setUsage] = useState<Usage | null>(null);
  const [memory, setMemory] = useState<Memory[]>([]);
  const [busy, setBusy] = useState<'review' | 'question' | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [question, setQuestion] = useState('');
  const [thread, setThread] = useState<{ me: string; reply: AnswerOutput | string }[]>([]);
  const [memoryEdit, setMemoryEdit] = useState<Memory | 'new' | null>(null);
  const [memoryText, setMemoryText] = useState('');
  const consent = profile.consent.ai_processing;

  const load = useCallback(async () => {
    if (mode !== 'account' || !consent || !navigator.onLine) return;
    const db = supabase();
    const [r, u, m] = await Promise.all([
      db.from('coach_reviews').select('id, created_at, period_from, period_to, review, model_id, prompt_version').order('created_at', { ascending: false }).limit(1),
      db.rpc('my_ai_usage'),
      db.from('user_confirmed_memory').select('id, fact').is('deleted_at', null).order('created_at'),
    ]);
    const row = r.data?.[0];
    if (row) {
      const body = row.review as { data_completeness: StoredReview['data_completeness']; output: StoredReview['output'] };
      setReview({ id: row.id, created_at: row.created_at, data_period: { from: row.period_from, to: row.period_to }, data_completeness: body.data_completeness, output: body.output, proposal_id: null, model_id: row.model_id, prompt_version: row.prompt_version });
      const p = await db.from('change_proposals').select('id, before_value, after_value, status').eq('coach_review_id', row.id).limit(1);
      setProposal((p.data?.[0] as Proposal | undefined) ?? null);
    }
    if (u.data) setUsage(u.data as Usage);
    setMemory((m.data ?? []) as Memory[]);
  }, [mode, consent]);

  useEffect(() => {
    const t = window.setTimeout(() => void load().catch(() => setMessage('Couldn’t load your coach history. Check your connection.')), 0);
    return () => window.clearTimeout(t);
  }, [load]);

  const getReview = async () => {
    setBusy('review');
    setMessage(null);
    const r = await callAi({ operation: 'weekly_review', today });
    setBusy(null);
    if (r.status === 'ok' && r.operation === 'weekly_review') {
      setReview(r.review);
      void load();
    } else setMessage(errorText(r));
  };

  const ask = async (q: string) => {
    const text = q.trim();
    if (text.length < 2) return;
    setBusy('question');
    setQuestion('');
    const r = await callAi({ operation: 'coach_question', today, question: text });
    setBusy(null);
    setThread((t) => [...t, { me: text, reply: r.status === 'ok' && r.operation === 'coach_question' ? r.answer : errorText(r) }]);
    void load();
  };

  const decide = async (accept: boolean) => {
    if (!proposal) return;
    const { error } = await supabase().rpc('decide_change_proposal', { p_proposal_id: proposal.id, p_decision: accept ? 'accepted' : 'rejected' });
    if (error) return notify({ kind: 'error', message: 'Couldn’t record your decision. Try again.' });
    if (accept) {
      await updateProfile({ ...profile, targets: { energy_kcal: proposal.after_value.energy_kcal, protein_g: proposal.after_value.protein_g, source: `Accepted from coach review ${formatShortDate(today)}` } });
      notify({ kind: 'info', message: 'Targets updated. You can change them any time in Settings.' });
    } else notify({ kind: 'info', message: 'Kept your current targets.' });
    void load();
  };

  const saveMemory = async () => {
    const fact = memoryText.trim().slice(0, 500);
    if (!fact) return;
    const db = supabase();
    const res = memoryEdit === 'new'
      ? await db.from('user_confirmed_memory').insert({ fact })
      : await db.from('user_confirmed_memory').update({ fact }).eq('id', (memoryEdit as Memory).id);
    if (res.error) return notify({ kind: 'error', message: 'Couldn’t save that note.' });
    setMemoryEdit(null);
    void load();
  };

  const deleteMemory = async (m: Memory) => {
    const { error } = await supabase().from('user_confirmed_memory').delete().eq('id', m.id);
    if (error) return notify({ kind: 'error', message: 'Couldn’t delete that note.' });
    void load();
  };

  const header = (
    <div className="row between">
      <button className="btn ghost" onClick={() => goBack('today')}><Icon name="chevronLeft" size={18} /> Back</button>
    </div>
  );

  if (mode === 'demo') {
    return (
      <div className="stack">
        {header}
        <div className="card coach">
          <EmptyState icon="sparkle" tone="coach" title="The coach works with your own journal" action={<button className="btn" onClick={exitDemo}>Leave demo and sign in</button>}>
            It reads only your own signed-in records — never demo data — and every review says which days it used and what’s missing.
          </EmptyState>
        </div>
      </div>
    );
  }

  if (!consent) {
    return (
      <div className="stack">
        {header}
        <div className="card coach stack">
          <span className="eyebrow">Coach</span>
          <div className="feature-title">Turn on AI help?</div>
          <ul className="small" style={{ margin: 0, paddingLeft: 18 }}>
            <li>Sends a short summary of your recent logs (no name or email), your question, or a photo you choose, through Rozana’s backend to Google’s Gemini API.</li>
            <li>Requests are stateless and not used to train models under the paid API terms; Google may still keep them briefly for abuse monitoring.</li>
            <li>Suggestions are proposals only. Nothing changes unless you accept.</li>
            <li>Logging never needs AI. You can turn this off any time in Settings.</li>
          </ul>
          <Toggle label="Allow AI help" checked={false} onChange={(v) => void updateProfile({ ...profile, consent: { ...profile.consent, ai_processing: v, updated_at: new Date().toISOString() } })} />
        </div>
      </div>
    );
  }

  return (
    <div className="stack" style={{ gap: 24 }}>
      {header}
      {!online ? <div className="notice warn">You’re offline. The coach needs a connection; logging still works.</div> : null}

      <Section title="Weekly review">
        <div className="card coach stack">
          {review ? <ReviewView review={review} proposal={proposal} onDecide={(a) => void decide(a)} /> : <p className="small">No review yet. It looks at the last 7 days of your own logs.</p>}
          <button className="btn" disabled={busy !== null || !online || (usage ? usage.reviews_week >= usage.limits.review_per_week : false)} onClick={getReview}>
            {busy === 'review' ? <><span className="spinner" /> Reviewing your week…</> : <><Icon name="sparkle" /> {review ? 'Get a new review' : 'Get this week’s review'}</>}
          </button>
          {usage ? <span className="label">{usage.limits.review_per_week - usage.reviews_week > 0 ? '1 new review available this week' : 'Next review available next week'}</span> : null}
          {message ? <div className="notice" role="status">{message} {busy === null ? <button className="link" onClick={getReview}>Try again</button> : null}</div> : null}
        </div>
      </Section>

      <Section title="Ask the coach">
        <div className="card stack">
          {thread.length === 0 ? (
            <div className="chips">{STARTERS.map((s) => <button key={s} className="chip" onClick={() => void ask(s)} disabled={busy !== null || !online}>{s}</button>)}</div>
          ) : (
            <div className="stack-sm" aria-live="polite">
              {thread.map((t, i) => (
                <div key={i} className="stack-sm">
                  <div className="bubble me">{t.me}</div>
                  <div className="bubble coach">{typeof t.reply === 'string' ? t.reply : t.reply.answer}</div>
                </div>
              ))}
            </div>
          )}
          <form className="row" onSubmit={(e) => { e.preventDefault(); void ask(question); }}>
            <input className="input grow" value={question} maxLength={500} placeholder="Ask a short question" aria-label="Your question" onChange={(e) => setQuestion(e.target.value)} />
            <button className="icon-btn filled" type="submit" aria-label="Send" disabled={busy !== null || !online || question.trim().length < 2}>
              {busy === 'question' ? <span className="spinner" /> : <Icon name="chevronRight" />}
            </button>
          </form>
          {usage ? <span className="label">{Math.max(0, usage.limits.question_per_day - usage.questions_today)} of {usage.limits.question_per_day} questions left today. Not for medical questions or symptoms.</span> : null}
        </div>
      </Section>

      <Section title="What the coach remembers" action={<button className="link" onClick={() => { setMemoryText(''); setMemoryEdit('new'); }}><Icon name="plus" size={16} /> Add</button>}>
        <div className="card tight list-divided">
          {memory.length === 0 ? <p className="small muted" style={{ padding: 8 }}>Nothing yet. Add facts you want it to keep in mind, like “I train before work”. It only remembers what you confirm here.</p> : memory.map((m) => (
            <div key={m.id} className="row" style={{ padding: '8px 0' }}>
              <span className="grow small">{m.fact}</span>
              <button className="icon-btn plain" aria-label={`Edit note: ${m.fact}`} onClick={() => { setMemoryText(m.fact); setMemoryEdit(m); }}><Icon name="edit" size={18} /></button>
              <button className="icon-btn plain" aria-label={`Delete note: ${m.fact}`} onClick={() => void deleteMemory(m)}><Icon name="trash" size={18} /></button>
            </div>
          ))}
        </div>
      </Section>

      {memoryEdit ? (
        <Sheet title={memoryEdit === 'new' ? 'Add a note' : 'Edit note'} onClose={() => setMemoryEdit(null)} actions={<button className="btn block" onClick={() => void saveMemory()}>Save</button>}>
          <textarea className="textarea" maxLength={500} value={memoryText} onChange={(e) => setMemoryText(e.target.value)} aria-label="Note" data-autofocus />
        </Sheet>
      ) : null}
    </div>
  );
}
