import { useCallback, useEffect, useState } from 'react';
import { useJournal } from '@/app/JournalContext';
import { goBack, navigate } from '@/app/router';
import { supabase } from '@/core/auth/supabase';
import { aiUsage, deleteThreads, latestOpenDraft, listThreads, type DraftRow, type ThreadSummary, type Usage } from '@/core/ai/coachData';
import { aiErrorText, callAi, reviewOutputFromStored, type StoredReview } from '@/core/ai/client';
import { Icon } from '@/core/design/icons';
import { Section, Sheet } from '@/core/design/ui';
import { formatShortDate } from '@/core/time/localDate';
import { AskCoachButton, AssistantBody, CoachGate, CoachScope } from './CoachParts';

interface Proposal { id: string; before_value: { energy_kcal: number | null; protein_g: number | null }; after_value: { energy_kcal: number | null; protein_g: number | null; rationale?: string }; status: string }
interface Memory { id: string; fact: string }

function ReviewView({ review, proposal, onDecide }: { review: StoredReview; proposal: Proposal | null; onDecide: (accept: boolean) => void }) {
  const o = review.output;
  const c = review.data_completeness;
  return (
    <div className="stack">
      <div className="row wrap" style={{ gap: 6 }}>
        <span className="tag coach">{formatShortDate(review.data_period.from)} – {formatShortDate(review.data_period.to)}</span>
        <span className="tag">{c.days_with_meals}/7 days with meals</span>
        <span className="tag">{c.sessions} workout{c.sessions === 1 ? '' : 's'}</span>
        <span className="tag">{c.weight_points} weigh-in{c.weight_points === 1 ? '' : 's'}</span>
      </div>
      {o.assistant_message ? <p className="small" style={{ margin: 0, whiteSpace: 'pre-wrap' }}>{o.assistant_message}</p> : null}
      {o.observations.length ? (
        <div className="review-block">
          <h3>What your logs show</h3>
          <ul>{o.observations.map((x, i) => <li key={i}>{x.text}</li>)}</ul>
        </div>
      ) : null}
      <AssistantBody output={{ ...o, questions: [] }} />
      {o.questions.length ? (
        <div className="review-block">
          <h3>Questions for you</h3>
          <ul>{o.questions.map((x) => <li key={x.id}>{x.text}</li>)}</ul>
        </div>
      ) : null}
      {proposal && proposal.status === 'proposed' ? (
        <div className="card flat stack-sm" style={{ background: 'var(--coach)', borderColor: 'transparent' }}>
          <strong>Proposed target change</strong>
          <div className="before-after">
            <div><div className="label">Now</div><div className="num">{proposal.before_value.energy_kcal ?? '—'} kcal<br />{proposal.before_value.protein_g ?? '—'} g protein</div></div>
            <Icon name="chevronRight" />
            <div><div className="label">Proposed</div><div className="num"><strong>{proposal.after_value.energy_kcal ?? '—'} kcal<br />{proposal.after_value.protein_g ?? '—'} g protein</strong></div></div>
          </div>
          {proposal.after_value.rationale ? <p className="small">{proposal.after_value.rationale}</p> : null}
          <div className="row">
            <button className="btn secondary grow" onClick={() => onDecide(false)}>Keep current</button>
            <button className="btn grow" onClick={() => onDecide(true)}>Accept</button>
          </div>
          <p className="label">Nothing changes unless you accept. Check big changes with a qualified professional.</p>
        </div>
      ) : proposal ? <p className="label">Target proposal {proposal.status === 'accepted' ? 'accepted' : 'kept as it was'}.</p> : null}
      <p className="label">
        Generated by {review.model_id} from your own records{review.legacy_v1 ? ' (older review format)' : ''}. It can be wrong; it isn’t medical advice.
      </p>
    </div>
  );
}

export function CoachScreen() {
  const header = (
    <div className="row" style={{ gap: 4 }}>
      <button className="icon-btn plain" aria-label="Back" onClick={() => goBack('today')}><Icon name="chevronLeft" /></button>
      <h1 className="sub-title grow">AI Coach</h1>
    </div>
  );
  return (
    <div className="stack" style={{ gap: 24 }}>
      <CoachGate header={header}>
        {header}
        <CoachHome />
      </CoachGate>
    </div>
  );
}

function CoachHome() {
  const { profile, updateProfile, today, notify } = useJournal();
  const online = navigator.onLine;
  const [review, setReview] = useState<StoredReview | null>(null);
  const [proposal, setProposal] = useState<Proposal | null>(null);
  const [usage, setUsage] = useState<Usage | null>(null);
  const [memory, setMemory] = useState<Memory[]>([]);
  const [threads, setThreads] = useState<ThreadSummary[] | null>(null);
  const [draft, setDraft] = useState<DraftRow | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [memoryEdit, setMemoryEdit] = useState<Memory | 'new' | null>(null);
  const [memoryText, setMemoryText] = useState('');
  const [confirmAll, setConfirmAll] = useState(false);

  const load = useCallback(async () => {
    if (!navigator.onLine) return;
    const db = await supabase();
    const [r, u, m, t, d] = await Promise.all([
      db.from('coach_reviews').select('id, created_at, period_from, period_to, review, model_id, prompt_version').order('created_at', { ascending: false }).limit(1),
      aiUsage(),
      db.from('user_confirmed_memory').select('id, fact').is('deleted_at', null).order('created_at'),
      listThreads().catch(() => []),
      latestOpenDraft().catch(() => null),
    ]);
    const row = r.data?.[0];
    if (row) {
      const body = row.review as { data_completeness: StoredReview['data_completeness']; output: unknown };
      const read = reviewOutputFromStored(body.output);
      if (read) {
        setReview({ id: row.id, created_at: row.created_at, data_period: { from: row.period_from, to: row.period_to }, data_completeness: body.data_completeness, output: read.output, legacy_v1: read.legacy_v1, proposal_id: null, model_id: row.model_id, prompt_version: row.prompt_version });
        const p = await db.from('change_proposals').select('id, before_value, after_value, status').eq('coach_review_id', row.id).limit(1);
        setProposal((p.data?.[0] as Proposal | undefined) ?? null);
      }
    }
    setUsage(u);
    setMemory((m.data ?? []) as Memory[]);
    setThreads(t);
    setDraft(d);
  }, []);

  useEffect(() => {
    const t = window.setTimeout(() => void load().catch(() => setMessage('Couldn’t load your coach history. Check your connection.')), 0);
    return () => window.clearTimeout(t);
  }, [load]);

  const getReview = async () => {
    setBusy(true);
    setMessage(null);
    const r = await callAi({ operation: 'weekly_review', today }, undefined, { timezone: profile.timezone });
    setBusy(false);
    if (r.status === 'ok' && r.operation === 'weekly_review') {
      setReview(r.review);
      void load();
    } else setMessage(aiErrorText(r));
  };

  const decide = async (accept: boolean) => {
    if (!proposal) return;
    const { error } = await (await supabase()).rpc('decide_change_proposal', { p_proposal_id: proposal.id, p_decision: accept ? 'accepted' : 'rejected' });
    if (error) return notify({ kind: 'error', message: 'Couldn’t record your decision. Try again.' });
    if (accept) {
      await updateProfile({ ...profile, targets: { energy_kcal: proposal.after_value.energy_kcal, protein_g: proposal.after_value.protein_g, source: `Accepted from coach review ${formatShortDate(today)}` } });
      notify({ kind: 'info', message: 'Targets updated. You can change them any time in Settings.' });
    } else notify({ kind: 'info', message: 'Kept your current targets.' });
    void load();
  };

  const saveMemory = async () => {
    const fact = memoryText.trim().slice(0, 500);
    if (!fact) return;
    const db = await supabase();
    const res = memoryEdit === 'new'
      ? await db.from('user_confirmed_memory').insert({ fact })
      : await db.from('user_confirmed_memory').update({ fact }).eq('id', (memoryEdit as Memory).id);
    if (res.error) return notify({ kind: 'error', message: 'Couldn’t save that note.' });
    setMemoryEdit(null);
    void load();
  };

  const deleteMemory = async (m: Memory) => {
    const { error } = await (await supabase()).from('user_confirmed_memory').delete().eq('id', m.id);
    if (error) return notify({ kind: 'error', message: 'Couldn’t delete that note.' });
    void load();
  };

  const removeThread = async (id: string | null) => {
    try {
      const n = await deleteThreads(id);
      setConfirmAll(false);
      notify({ kind: 'info', message: id ? 'Chat deleted.' : `${n} chat${n === 1 ? '' : 's'} deleted. Saved notes are kept.` });
      void load();
    } catch (e) {
      notify({ kind: 'error', message: (e as Error).message });
    }
  };

  return (
    <>
      {!online ? <div className="notice warn">You’re offline. The coach needs a connection; logging still works.</div> : null}
      <CoachScope />

      <div className="card coach stack">
        <span className="eyebrow">AI Coach</span>
        <div className="feature-title">Ask about your training, food or week</div>
        <p className="small" style={{ margin: 0 }}>Answers use your own records and usual foods. Plan changes and saved notes always need your OK.</p>
        <AskCoachButton />
        {usage ? <span className="label">{Math.max(0, usage.limits.question_per_day - usage.questions_today)} of {usage.limits.question_per_day} messages left today</span> : null}
      </div>

      {draft ? (
        <button className="card train" style={{ textAlign: 'left', width: '100%', color: 'inherit' }} onClick={() => navigate('draft', draft.id)}>
          <span className="eyebrow">Plan draft</span>
          <span className="feature-title" style={{ display: 'block' }}>{draft.plan.title}</span>
          <span className="small">{draft.plan.days.length} day{draft.plan.days.length === 1 ? '' : 's'} · from {formatShortDate(draft.created_at.slice(0, 10))}. Review it: nothing changes until you accept.</span>
        </button>
      ) : null}

      <Section title="Recent chats" action={threads?.length ? <button className="link" onClick={() => setConfirmAll(true)}>Delete all</button> : undefined}>
        <div className="card tight list-divided">
          {threads === null ? <div className="skeleton" /> : threads.length === 0 ? (
            <p className="small muted" style={{ padding: 8 }}>No chats yet. Chats are kept for 90 days after your last message, or until you delete them.</p>
          ) : threads.map((t) => (
            <div key={t.id} className="row" style={{ padding: '6px 0' }}>
              <button className="ex-row grow" style={{ padding: '8px 0' }} onClick={() => navigate('chat', t.id)}>
                <span className="grow"><span className="er-name">{t.title}</span><br /><span className="er-sub">{formatShortDate(t.updated_at.slice(0, 10))}</span></span>
              </button>
              <button className="icon-btn plain" aria-label={`Delete chat: ${t.title}`} onClick={() => void removeThread(t.id)}><Icon name="trash" size={18} /></button>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Weekly review">
        <div className="card coach stack">
          {review ? <ReviewView review={review} proposal={proposal} onDecide={(a) => void decide(a)} /> : <p className="small">No review yet. It looks at the last 7 days of your own logs.</p>}
          <button className="btn" disabled={busy || !online || (usage ? usage.reviews_week >= usage.limits.review_per_week : false)} onClick={getReview}>
            {busy ? <><span className="spinner" /> Reviewing your week…</> : <><Icon name="sparkle" /> {review ? 'Get a new review' : 'Get this week’s review'}</>}
          </button>
          {usage ? <span className="label">{usage.limits.review_per_week - usage.reviews_week > 0 ? '1 new review available this week' : 'Next review available next week'}</span> : null}
          {message ? <div className="notice" role="status">{message} {!busy ? <button className="link" onClick={getReview}>Try again</button> : null}</div> : null}
        </div>
      </Section>

      <Section title="What the coach remembers" action={<button className="link" onClick={() => { setMemoryText(''); setMemoryEdit('new'); }}><Icon name="plus" size={16} /> Add</button>}>
        <div className="card tight list-divided">
          {memory.length === 0 ? <p className="small muted" style={{ padding: 8 }}>Nothing yet. Add facts you want it to keep in mind, like “I train before work”. It only remembers what you confirm. Deleting a chat doesn’t delete these.</p> : memory.map((m) => (
            <div key={m.id} className="row" style={{ padding: '8px 0' }}>
              <span className="grow small">{m.fact}</span>
              <button className="icon-btn plain" aria-label={`Edit note: ${m.fact}`} onClick={() => { setMemoryText(m.fact); setMemoryEdit(m); }}><Icon name="edit" size={18} /></button>
              <button className="icon-btn plain" aria-label={`Delete note: ${m.fact}`} onClick={() => void deleteMemory(m)}><Icon name="trash" size={18} /></button>
            </div>
          ))}
        </div>
      </Section>

      {memoryEdit ? (
        <Sheet title={memoryEdit === 'new' ? 'Add a note' : 'Edit note'} onClose={() => setMemoryEdit(null)} actions={<button className="btn block" onClick={() => void saveMemory()}>Save</button>}>
          <textarea className="textarea" maxLength={500} value={memoryText} onChange={(e) => setMemoryText(e.target.value)} aria-label="Note" data-autofocus />
        </Sheet>
      ) : null}
      {confirmAll ? (
        <Sheet title="Delete all chats?" onClose={() => setConfirmAll(false)} actions={
          <>
            <button className="btn secondary grow" onClick={() => setConfirmAll(false)}>Keep</button>
            <button className="btn danger grow" onClick={() => void removeThread(null)}>Delete all</button>
          </>
        }>
          <p className="muted">Every chat is removed from your account now. “What the coach remembers” is kept until you delete those notes.</p>
        </Sheet>
      ) : null}
    </>
  );
}
